---
minimum_pre_commit_version: 3.0.0

repos:
  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend-lint
        entry: bunx lint-staged
        pass_filenames: false
        language: system

      - id: expo-doctor
        name: expo-doctor
        entry: bash -c "bunx expo-doctor ./*"
        pass_filenames: false
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.12.1
    hooks:
      - id: zizmor
        args:
          - --fix=all

  - repo: https://github.com/crate-ci/typos
    rev: v1.36.3
    hooks:
      - id: typos
        types_or: [markdown, python, ts, tsx]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
